### ISSUE TITLE
Possible bug report - missing lastposter image in UCP

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/flap#4]
Missing last poster avatar in a forum subscription page in UCP

(I assume that this should be noted because this bug is in your "unreleased" version of Last Poster plugin from Tom M.).

![image](https://user-images.githubusercontent.com/778890/50575426-b2da8e00-0dff-11e9-83e4-42b4133039c7.png)

**Comment by effone** [comment]
This plugin is being coded from the scratch with a completely new approach and no way related to Tomm's one.
UCP part is not yet touched. Follow the feature checklist in Readme to see what implemented so far. 

You can install the plugin as is and check. It is fully functional with the parts that implemented.
